In [25]:
with open('input.txt', 'r', encoding='utf-8') as file:
    data = file.read()
print("the legth is :", len(data))

the legth is : 1115394


In [26]:
chars = sorted(list(set(data)))
print("the unique chars are :", ''.join(chars))
print("the number of vocabulary is :", len(chars))

the unique chars are : 
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
the number of vocabulary is : 65


In [27]:
#maps from char to int
char_to_int = {ch: i for i, ch in enumerate(chars)}
#maps from int to char
int_to_char = {i: ch for i, ch in enumerate(chars)}
#function to encode a string to a list of integers
encode = lambda s: [char_to_int[c] for c in s]
#function to decode a list of integers to a string
decode = lambda l: ''.join([int_to_char[i] for i in l])

#example usage
enc = encode("mihmoret")
print(enc)
dec = decode(enc)
print(dec)
#example of handling character not in the vocabulary
try:
    enc2 = encode("+")
except KeyError as e:
    print(f"Error: {e} is not in the character set.")


[51, 47, 46, 51, 53, 56, 43, 58]
mihmoret
Error: '+' is not in the character set.


In [28]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("using device:", device)
#copying the data
text = data

data = torch.tensor(encode(text), dtype=torch.long, device=device)
print(data.shape, data.dtype, data.device)
print(data[:100])


using device: cuda
torch.Size([1115394]) torch.int64 cuda:0
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59], device='cuda:0')


In [29]:
#split the data into train and validation sets.
#since we are doing pretrain , we can split it naively
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

block_size = 8

In [30]:
#Demonstration of how to create input and gt
#given x guess next char . y is gt
x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    context = x[:t + 1]
    target = y[t]
    print(f"when input is {context.tolist()} the target is {target.item()}")

when input is [18] the target is 47
when input is [18, 47] the target is 56
when input is [18, 47, 56] the target is 57
when input is [18, 47, 56, 57] the target is 58
when input is [18, 47, 56, 57, 58] the target is 1
when input is [18, 47, 56, 57, 58, 1] the target is 15
when input is [18, 47, 56, 57, 58, 1, 15] the target is 47
when input is [18, 47, 56, 57, 58, 1, 15, 47] the target is 58


In [31]:
torch.manual_seed(1337)
batch_size = 4  #how many independent sequences will we process in parallel
block_size = 8  #what is the maximum context length for predictions


def get_batch(split):
    """
    :param split: 'train' or 'val' to specify which dataset to use.
    :return: A tuple (x, y) where x is a tensor of shape (batch_size, block_size) containing input token indices and y is a tensor of shape (batch_size, block_size) containing target token indices.
    """
    #generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))  # 4 random starting indices along the data
    x = torch.stack([data[i:i + block_size] for i in ix])  # 4 sequences of length block_size , 4X8 tensor.
    y = torch.stack(
        [data[i + 1:i + block_size + 1] for i in ix])  # 4 sequences of length block_size , 4X8 tensor.the labels.
    return x, y


xb, yb = get_batch('train')
xb.to('cuda')
yb.to('cuda')
print("inputs:")
print(xb.shape)
print(xb)
print("outputs:")
print(yb.shape)
print(yb)
print("---")

#example of input and target.

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t + 1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} the target is {target.item()}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]], device='cuda:0')
outputs:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]], device='cuda:0')
---
when input is [24] the target is 43
when input is [24, 43] the target is 58
when input is [24, 43, 58] the target is 5
when input is [24, 43, 58, 5] the target is 57
when input is [24, 43, 58, 5, 57] the target is 1
when input is [24, 43, 58, 5, 57, 1] the target is 46
when input is [24, 43, 58, 5, 57, 1, 46] the target is 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target is 39
when input is [44] the target is 53
when input is [44, 53] the target is 56
when input is [44, 53, 56] the target is 1
when input is [44, 53, 56, 1] the target is 58
when input is

Creating the bigram language model And training it.

In [32]:
#bigram model
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1337)


class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        #each row represents a token id , and each mat[i,j] is the score for jth token in the vocab given ith token.
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        """

        :param idx: a tensor of shape (batch_size, block_size) containing input token indices.
        :param targets: the same as idx , but containing the targets
        :return: a tensor of shape (batch_size*block_size, vocab_size) containing logits and the loss.
        """
        #idx is the Batch_size X Time/context tensor of input token indices .
        logits = self.token_embedding_table(idx)  #BXTXC(Channels). for each token , there is a distribution of logits.
        if targets is None: #during inference.
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)  # (BXT)XC. reshaping for loss computation 3d to 2d.
            targets = targets.view(B * T)  # (BXT) . reshaping for loss computation 2d to 1d.
            #how well we are predicting the targets
            loss = F.cross_entropy(logits, targets) #for example target is index 3 , so softmax(logits) , then loss = -log(sm_logits[3]).
            #for each entry we will return the logits for the next token and the loss.
        return logits, loss

    def generate(self, idx, max_new_tokens):
        """

        :param idx: a tensor of shape (batch_size, time) containing input token indices.
        :param max_new_tokens: the number of new tokens you want to generate.
        :return: a tensor of shape (batch_size, time + max_new_tokens) containing the input token indices followed by the generated token indices.
        """
        #idx is a BXT tensor of input token
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]  #BXC  , for each batch we take the predictions for the last token.
            probs = F.softmax(logits, dim=-1)  #BXC , converting to probabilities
            idx_next = torch.multinomial(probs, num_samples=1)  #BX1 , the next predicted token for each batch.
            idx = torch.cat((idx, idx_next), dim=1)  # BX(T+1) , appending the predicted token to the input sequence.
        return idx


m = BigramLanguageModel(vocab_size=len(chars)).to(device)
out, loss = m(xb, yb)
print(out)
print(out.shape)
print(loss)

# a tensor with a single zero , B=1 , T=1 , representing the start token.
idx = torch.zeros((1, 1), dtype=torch.long, device=device)
#generating 100 new tokens , since the embd table randomly initialized , the output will be random characters.
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))


tensor([[-1.5101, -0.0948,  1.0927,  ..., -0.6126, -0.6597,  0.7624],
        [ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594],
        [ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305],
        ...,
        [-2.1910, -0.7574,  1.9656,  ..., -0.3580,  0.8585, -0.6161],
        [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
        [-0.6787,  0.8662, -1.6433,  ...,  2.3671, -0.7775, -0.2586]],
       device='cuda:0', grad_fn=<ViewBackward0>)
torch.Size([32, 65])
tensor(4.8786, device='cuda:0', grad_fn=<NllLossBackward0>)

pYCXxfRkRZd
wc'wfNfT;OLlTEeC K
jxqPToTb?bXAUG:C-SGJO-33SM:C?YI3a
hs:LVXJFhXeNuwqhObxZ.tSVrddXlaSZaNe


In [33]:
#training the model , defining the optimizer.
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
batch_size = 32  #how many independent sequences will we process in parallel
for steps in range(2501):
    #get a batch of data
    xb, yb = get_batch('train')
    #evaluate the loss
    logits, loss = m(xb, yb)
    #backpropagation
    optimizer.zero_grad(set_to_none=True)  #set gradients to zero , to avoid accumulation from previous step.
    loss.backward()  # compute gradients , see how much each weight contributed to the loss.
    optimizer.step()
    if steps % 500 == 0:
        print(steps, loss.item())

0 4.648483753204346
500 4.162596702575684
1000 3.7026753425598145
1500 3.4229278564453125
2000 3.1231143474578857
2500 3.026318073272705


In [34]:
 #geenrating a  1 degree  tensor of predicted tokens , then decoding and printing them.
print(decode(m.generate(idx, max_new_tokens=300)[0].tolist()))
out, loss = m(xb, yb)
print(out)
print(loss)


WIw3cHPy Wk,f'sta-omzotom:
Yow&$FMOUf isth bHEv!$Whedilin,

3:ireeYERngmin;latiHFlililv Es, ateqWk p.
GRW.
Swabo!
el.lind peal.
-huD3SPy wiry:CUEOKMOissphiw y. w'sBHUSInoBoopeYelgCIEJMk:
Gll, d motSPklloaW-wNA whrVCeiib3s wor m dE$HZAETENGShireAs C-LK3:Cl-xTre

ALkOMmnterupteA so;; irDWWTo:CENuCIy.

tensor([[-0.8230,  0.2956, -0.7149,  ...,  0.2811,  1.2906, -1.2587],
        [ 0.2202,  2.0440, -0.8370,  ..., -1.0215, -0.4710, -2.6265],
        [-0.5402,  1.1978,  1.4507,  ..., -1.8027,  1.0798, -1.1982],
        ...,
        [-0.3019, -1.5985, -2.6523,  ..., -0.6410,  0.0936, -0.9586],
        [-0.8230,  0.2956, -0.7149,  ...,  0.2811,  1.2906, -1.2587],
        [-0.8230,  0.2956, -0.7149,  ...,  0.2811,  1.2906, -1.2587]],
       device='cuda:0', grad_fn=<ViewBackward0>)
tensor(3.0259, device='cuda:0', grad_fn=<NllLossBackward0>)


A toy example of how tokens refer to each other during self attention.

In [35]:
B, T, C = 4, 8, 2  #batch size , time steps , channels
x = torch.randn(B, T, C, device=device)
xbow = torch.zeros((B, T, C), device=device)  # bow is "bag of words"
for b in range(B):
    for t in range(T):
        xprev = x[b, :t + 1]  #t+1 because we want to include the current time step  . TXC
        xbow[b, t] = torch.mean(xprev, dim=0)  #make the t'th token enriched with the average of all previous tokens including itself. 1XC.


print("the tokens for batch 0:", x[0])
print("enriched tokens for batch 0 :", xbow[0])

the tokens for batch 0: tensor([[-0.5297, -1.2233],
        [-0.7130,  1.6656],
        [-1.8076,  0.9520],
        [ 0.0940,  0.1593],
        [ 0.9399, -0.7818],
        [-0.0746, -3.1373],
        [ 0.3023,  0.1123],
        [ 0.4201, -0.4124]], device='cuda:0')
enriched tokens for batch 0 : tensor([[-0.5297, -1.2233],
        [-0.6213,  0.2212],
        [-1.0168,  0.4648],
        [-0.7391,  0.3884],
        [-0.4033,  0.1544],
        [-0.3485, -0.3943],
        [-0.2555, -0.3219],
        [-0.1711, -0.3332]], device='cuda:0')


Second attempt , using matrix multiplication.

In [36]:
torch.manual_seed(42)
#torch.tril return lower triangular part of the matrix , e.g. future mask.
a = torch.tril(torch.ones(3, 3)).to(device)
a_row_sum = torch.sum(a ,dim=1 , keepdim=True) #sums over the rows of a
print(a_row_sum.shape)
a = a / a_row_sum  #normalize so that each row sums to 1 , element wise division.
b = torch.randint(0, 10, (3, 2)).float().to(device) #random matrix representing the input tokens , 3 time steps and 2 channels.
c = a @ b
print("a:")
print(a)
print("b:")
print(b)
print("c:")
print(c)

torch.Size([3, 1])
a:
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]], device='cuda:0')
b:
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]], device='cuda:0')
c:
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]], device='cuda:0')


In [37]:
wei = torch.tril(torch.ones(T, T)).to(device) #lower triangular matrix for masking.
wei = wei / torch.sum(wei, dim=1, keepdim=True) #normalize the matrix.
xbow2 = wei @ x  # TXT X BXTXC ---> BXTXT X BXTXC --> BXTXC (this operation is valid due to special rules for batched matrices , the Batch dimension is being ignored)
print("iterative approach and matrix mult approach are giving the same result") if torch.allclose(xbow, xbow2 , atol=1e-05 , rtol=1e-06) else print("")


iterative approach and matrix mult approach are giving the same result


Using Softmax

In [38]:
tril = torch.tril(torch.ones(T, T)).to(device)
print(tril)
wei = torch.zeros(T, T, device=device)
#upper triangular part to -inf else 0 , restricting attention to previous tokens only.
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)  #softmax along the rows
xbow3 = wei @ x
torch.allclose(xbow2, xbow3)  #matrices are equivalent



tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]], device='cuda:0')


True

Now implementing self attention mechanism.

In [39]:
torch.manual_seed(1337)
B, T, C = 4, 8, 32  #batch size , time , channels .
x = torch.randn(B, T, C).to(device)

#single head self attention
head_size = 16
#creating 3 linear layers that will convert the input tokens from dim C to dim head.
key = nn.Linear(C, head_size, bias=False).to(device)
query = nn.Linear(C, head_size, bias=False).to(device)
value = nn.Linear(C, head_size, bias=False).to(device)
k = key(x)  # BXTXhead_size
q = query(x)  # BXTXhead_size
#getting a BXTXT matrix of attention weights. scaling since dot product becomes larger as the vectors are longer , so the softmax will be too sharp.
wei = q @ k.transpose(-2, -1) * (head_size ** -0.5)
tril = torch.tril(torch.ones(T, T)).to(device) #future mask.
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)  #softmax along the rows
v = value(x)  # BXTXhead_size
out = wei @ v #BXTXhead_size.
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3966, 0.6034, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3069, 0.2892, 0.4039, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3233, 0.2175, 0.2443, 0.2149, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1479, 0.2034, 0.1663, 0.1455, 0.3369, 0.0000, 0.0000, 0.0000],
        [0.1259, 0.2490, 0.1324, 0.1062, 0.3141, 0.0724, 0.0000, 0.0000],
        [0.1598, 0.1990, 0.1140, 0.1125, 0.1418, 0.1669, 0.1061, 0.0000],
        [0.0845, 0.1197, 0.1078, 0.1537, 0.1086, 0.1146, 0.1558, 0.1553]],
       device='cuda:0', grad_fn=<SelectBackward0>)

Bigram model  , with a single attention head .

In [40]:

import torch.nn as nn

torch.manual_seed(1337)

n_embd = 32
vocab_size = len(chars)


#implementing single head self attention as a nn.Module
class Head(nn.Module):
    """
    Self Attention module
    """
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)  #key , what to look for
        self.query = nn.Linear(n_embd, head_size, bias=False)  #query , what to match with
        self.value = nn.Linear(n_embd, head_size, bias=False)  #value , what to return
        #register it in a buffer so pytorch will move it to gpu along with the rest , and won't count it as regular attribute.
        self.register_buffer('tril',
                             torch.tril(torch.ones(block_size, block_size)))  #lower triangular matrix for masking



    def forward(self, x):
        """

        :param x: a tensor of shape (batch_size, time, channels) containing the input token representations.
        :return: the enriched representation after applying self attention.
        """
        B, T, C = x.shape
        k = self.key(x)  # BXTXhead_size
        q = self.query(x)  # BXTXhead_size
        wei = q @ k.transpose(-2, -1) * (k.shape[-1] ** -0.5)  #scaling factor , for softmax stability .
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)  #softmax along the rows
        v = self.value(x)  # BXTXhead_size
        out = wei @ v
        return out


class BigramLanguageModel(nn.Module):
    """

    """
    def __init__(self):
        #each row represents a token id , and each mat[i,j] is the score for jth token in the vocab given ith token.
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)  #for each token we get a vector its representation.
        self.lm_head = nn.Linear(n_embd, vocab_size) #shrinking the original dim to lower dim.
        self.sa_head = Head(n_embd)  #self attention head
        self.position_embedding_table = nn.Embedding(block_size,
                                                     n_embd)  #representation of the position of the token in the sequence.

    def forward(self, idx, targets=None):
        """

        :param idx: a tensor of shape (batch_size, time) containing the tokens indices.
        :param targets: a tensor of shape (batch_size, time) containing the target tokens.
        :return: the raw logits for each batch and the loss for this batch.
        """
        B, T = idx.shape
        token_emb = self.token_embedding_table(idx)  #BXTXC.
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))  #TXC  .
        x = token_emb + pos_emb  #BXTXC , adding token embedding and position embedding.
        x = self.sa_head(x)  #applying self attention , making the x tokens enriched with context from previous tokens.
        logits = self.lm_head(x)  #BXTXvocab_size , projection to have a raw score for each next token.
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)  # (BXT)XC. reshaping for loss computation 3d to 2d.
            targets = targets.view(B * T)  # (BXT) . reshaping for loss computation 2d to 1d.
            #how well we are predicting the targets
            loss = F.cross_entropy(logits, targets)
            #for each entry we will return the logits for the next token.
        return logits, loss

    def generate(self, idx, max_new_tokens):
        """

        :param idx: a tensor of shape (batch_size, time) containing the tokens indices.
        :param max_new_tokens: number of tokens to generate
        :return: the generated tokens with the input (t+max_new_tokens)
        """
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]  #conditioning only on the last block_size tokens. for now 2.
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]  #BXC  , for each batch we take the predictions for the last token.
            probs = F.softmax(logits, dim=-1)  #BXC , converting to probabilities
            idx_next = torch.multinomial(probs, num_samples=1)  #BX1 , the next predicted token for each batch.
            idx = torch.cat((idx, idx_next), dim=1)  # BX(T+1) , appending the predicted token to the input sequence.
        return idx


m = BigramLanguageModel().to(device)
out, loss = m(xb, yb)
optimizer = torch.optim.Adam(m.parameters(), lr=0.001)
#training the model , as before.
batch_size = 32  #how many independent sequences will we process in parallel
for steps in range(1000):
    #get a batch of data
    xb, yb = get_batch('train')
    #evaluate the loss
    logits, loss = m(xb, yb)
    #backpropagation
    optimizer.zero_grad(set_to_none=True)  #set gradients to zero , to avoid accumulation from previous step.
    loss.backward()  # compute gradients , see how much each weight contributed to the loss.
    optimizer.step()
    if steps % 200 == 0:
        print(steps, loss.item())


0 4.3332600593566895
200 3.0554254055023193
400 2.729879856109619
600 2.596479892730713
800 2.466625213623047


In [41]:
print(decode(m.generate(idx, max_new_tokens=300)[0].tolist()))


Whent ikitridcowi,
T is b, bte

Hiset bube ule.
S:
O-ans mealatauss ar bthif uw he, vete redthas ate awice my.

HDEEarut orour
Yowthertof isth bet mil ndilincaes iree sengcin lat HFridrov te, anen m pnganr.
Trans!
el lind me ut liser onchiry wture aiss hewty.
Hllinte korfopetelaves
Mk:
Ill, dl tthak


Now multiple heads of self attention , as well as MLP layer for better representation power.

In [42]:

import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1337)

n_embd = 32
vocab_size = len(chars)


class MultiHeadAttention(nn.Module):
    """
    getting multiple self attention to work parrelly and then concatenating their outputs together to get a richer representation.
    """
    def __init__(self, num_heads, head_size):
        super().__init__()
        #create a list of multiple heads.
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])

    def forward(self, x):
        #concatenate the output of each head along the channel dimension , basically stacking them.
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return out


class FeedForward(nn.Module):

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, n_embd), nn.ReLU()
        )

    def forward(self, x):
        return self.net(x)


class BigramLanguageModel(nn.Module):
    """
    Bigram Language Model with multiple heads of self attention and a feed forward layer for better representation power.
    """
    def __init__(self):
        #each row represents a token id , and each mat[i,j] is the score for jth token in the vocab given ith token.
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)  #for each token we get a vector its representation.
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.sa_heads = MultiHeadAttention(num_heads=4,
                                           head_size=n_embd // 4)  #self attention head , num_heads * head_size = n_embd
        self.ffwd = FeedForward(n_embd)  #feed forward layer
        self.position_embedding_table = nn.Embedding(block_size,
                                                     n_embd)  #representation of the position of the token in the sequence.

    def forward(self, idx, targets=None):
        B, T = idx.shape
        #idx is the BXT tensor of input token indices .
        token_emb = self.token_embedding_table(idx)  #BXTXC.
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))  #TXC  .
        x = token_emb + pos_emb  #BXTXC , adding token embedding and position embedding.
        x = self.sa_heads(x)  #applying self attention , making the x tokens enriched with context from previous tokens.
        x = self.ffwd(x)  #applying feed forward layer.
        logits = self.lm_head(x)  #BXTXvocab_size
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)  # (BXT)XC. reshaping for loss computation 3d to 2d.
            targets = targets.view(B * T)  # (BXT) . reshaping for loss computation 2d to 1d.
            #how well we are predicting the targets
            loss = F.cross_entropy(logits, targets)
            #for each entry we will return the logits for the next token.
        return logits, loss

    def generate(self, idx, max_new_tokens):
        #idx is a BXT tensor of input token
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]  #conditioning only on the last block_size tokens.
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]  #BXC  , for each batch we take the predictions for the last token.
            probs = F.softmax(logits, dim=-1)  #BXC , converting to probabilities
            idx_next = torch.multinomial(probs, num_samples=1)  #BX1 , the next predicted token for each batch.
            idx = torch.cat((idx, idx_next), dim=1)  # BX(T+1) , appending the predicted token to the input sequence.
        return idx





In [43]:
m = BigramLanguageModel().to(device)
out, loss = m(xb, yb)
optimizer = torch.optim.Adam(m.parameters(), lr=0.001)
#training the model , as before.
batch_size = 32  #how many independent sequences will we process in parallel
for steps in range(5000):
    #get a batch of data
    xb, yb = get_batch('train')
    xb_v , yb_v = get_batch('val')
    #evaluate the loss
    logits, loss = m(xb, yb)
    _, val_loss = m(xb_v , yb_v)
    #backpropagation
    optimizer.zero_grad(set_to_none=True)  #set gradients to zero , to avoid accumulation from previous step.
    loss.backward()  # compute gradients , see how much each weight contributed to the loss.
    optimizer.step()
    if steps % 500 == 0:
        print(steps, loss.item(), val_loss.item())

0 4.192056655883789 4.203073501586914
500 2.515002965927124 2.5795841217041016
1000 2.4714395999908447 2.430717945098877
1500 2.45752215385437 2.3945536613464355
2000 2.2318344116210938 2.3154497146606445
2500 2.4084348678588867 2.395378351211548
3000 2.261319637298584 2.176138401031494
3500 2.2730906009674072 2.2613821029663086
4000 2.157097578048706 2.419206142425537
4500 2.237255334854126 2.3156919479370117


In [44]:
 print(decode(m.generate(idx, max_new_tokens=300)[0].tolist()))


When bef bry cowi, he son, be madisen bobe don anthend my dalatanss:
Wanth fun qure vet?
Fedtlas anes wice my.

HDER:
An onome
Yowns, tof is he me mil; dill, at mireees, hein latist id ove so and to pordir.

Wansesel lind peave lis my now by pruge aissellwoy.
Hust, us orfood sigh gond thy wod moth k


Scaled model with layer norm and residual connections.

In [45]:

import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1337)
#defining hyperparameters
batch_size = 32
block_size = 128
learning_rate = 3e-4
n_layer = 6
n_heads = 6
n_embd = 384
dropout = 0.2
vocab_size = len(chars)


class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        #create a list of multiple heads.
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(num_heads * head_size, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.proj(out)
        return out


class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout)  #adding dropout for regularization
        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    """
    defines a block of a pre-LN decoder.
    masked layer norm --> multi head attention --> residual connection --> layer norm --> feed forward --> residual connection.
    """
    def __init__(self, n_embd, num_heads):
        super().__init__()
        head_size = n_embd // num_heads
        self.sa = MultiHeadAttention(num_heads, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))  #residual connection , normalize before transforming.
        x = x + self.ffwd(self.ln2(x))  #residual connection , normalize before transforming.
        return x


class BigramLanguageModel(nn.Module):
    """
    Full Decoder model
    indices - > embeddings + positional embeddings -> blocks of transformer -> layer norm -> linear layer -> logits for next token prediction.
    """
    def __init__(self):
        #each row represents a token id , and each mat[i,j] is the score for jth token in the vocab given ith token.
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)  #for each token we get a vector its repr'.
        self.position_embedding_table = nn.Embedding(block_size,
                                                     n_embd)  #repr' of the position of the token in the sequence.
        self.blocks = nn.Sequential(
            *[Block(n_embd, num_heads=n_heads) for _ in range(n_layer)])  #stacking multiple blocks
        self.ln_f = nn.LayerNorm(n_embd)  #final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        #idx is the BXT tensor of input token indices .
        token_emb = self.token_embedding_table(idx)  #BXTXC.
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))  #TXC  .
        x = token_emb + pos_emb  #BXTXC , adding token embedding and position embedding.
        x = self.blocks(x)  #applying self attention , making the x tokens enriched with context from previous tokens.
        x = self.ln_f(x)  #applying feed forward layer.
        logits = self.lm_head(x)  #BXTXvocab_size
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)  # (BXT)XC. reshaping for loss computation 3d to 2d.
            targets = targets.view(B * T)  # (BXT) . reshaping for loss computation 2d to 1d.
            #how well we are predicting the targets
            loss = F.cross_entropy(logits, targets)
            #for each entry we will return the logits for the next token.
        return logits, loss

    def generate(self, idx, max_new_tokens):
        #idx is a BXT tensor of input token
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]  #conditioning only on the last block_size tokens.
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]  #BXC  , for each batch we take the predictions for the last token.
            probs = F.softmax(logits, dim=-1)  #BXC , converting to probabilities
            idx_next = torch.multinomial(probs, num_samples=1)  #BX1 , the next predicted token for each batch.
            idx = torch.cat((idx, idx_next), dim=1)  # BX(T+1) , appending the predicted token to the input sequence.
        return idx





In [48]:

m = BigramLanguageModel().to(device)
out, loss = m(xb, yb)
optimizer = torch.optim.Adam(m.parameters(), lr=0.001)
#training the model , as before.
batch_size = 64  #how many independent sequences will we process in parallel
for steps in range(1000):
    #get a batch of data
    xb, yb = get_batch('train')
    xb_val, yb_val = get_batch('val')
    #evaluate the loss
    logits, loss = m(xb, yb)
    _, val_loss = m(xb_val, yb_val)
    #backpropagation
    optimizer.zero_grad(set_to_none=True)  #set gradients to zero , to avoid accumulation from previous step.
    loss.backward()  # compute gradients , see how much each weight contributed to the loss.
    optimizer.step()
    if steps % 10 == 0:
        print(steps, loss.item(), val_loss.item())

0 4.390467166900635 4.359597206115723
10 3.302518367767334 3.3708982467651367
20 2.929633617401123 2.931149959564209
30 2.693634510040283 2.6997785568237305
40 2.5903942584991455 2.617389678955078
50 2.5635268688201904 2.549354076385498
60 2.517693519592285 2.5170834064483643
70 2.494988203048706 2.5147864818573
80 2.4582271575927734 2.486903667449951
90 2.4747159481048584 2.489417314529419
100 2.4273486137390137 2.4799132347106934
110 2.4186272621154785 2.4480605125427246
120 2.3909356594085693 2.4156532287597656
130 2.42294979095459 2.368962049484253
140 2.375082492828369 2.3952784538269043
150 2.312614917755127 2.343493700027466
160 2.2706499099731445 2.2789292335510254
170 2.2145633697509766 2.248114585876465
180 2.174039840698242 2.2401890754699707
190 2.1391353607177734 2.166677474975586
200 2.1047277450561523 2.1535568237304688
210 2.0616040229797363 2.1424717903137207
220 2.0497331619262695 2.1311957836151123
230 2.028792142868042 2.0465950965881348
240 1.9765311479568481 2.048

In [49]:
print(decode(m.generate(idx, max_new_tokens=1000)[0].tolist()))


WARWICK:
Ay, bid Henry, God afford, alack! what with secreads
her scleak these innupting all the king's round truish!
Fear he remedy and how would do him resolt Go, but,
Becaugnow me hath made not-time a monty;
At in posmagy prays too trive thee,
The full obear again;
Let eld here stoles or both: joy as beting
be and to thee weak be meephen.

First Servingman:
But in one my structite myself,
With must foul is well so thing in way,
Meethough we biflesh weithed, to the service

More of son:
Our stiery in pright, Clifford my hands.

GLOUCESTER:
Not shug a gates unto me it hath bloody and spoin you arrain,
Fith your bode; of despards after;
But I learn yet all reason to the flaces of all;
Such night had And been look'd against of vantage,
his is drief so sarce of ur earleth great.

PETRUCHIO:
Would would grief thou body.

ROMEO:
And 'nough the graces of heaven Give me of so;
The execure these loads, our fallshould cleaks thee
is acento stieed to him to hath all on, please.

ANGELO:
Now, i

In [ ]:
#write the generated text to a file
generated_text = decode(m.generate(idx, max_new_tokens=1000)[0].tolist())
with open('generated_text.txt', 'w', encoding='utf-8') as file:
    file.write(generated_text)
